- meta/ThresholdCorrections.m
- meta/WeinbergAngle.m
- templates/weinberg_angle.cpp.in
- templates/weinberg_angle.hpp.in
- test/test_CMSSMNoFV_weinberg_angle_meta.cpp
- test/test_CMSSM_weinberg_angle_meta.cpp
- test/test_SM_weinberg_angle_meta.cpp
improvements in muon decay implementation
> Feature 2.0

- meta/EDM.m
> Fixed index issue analogous to 7e8121905bb795066afcb5ab032dc8da0708cb85

- src/numerics.cpp
> replace std::abs() by local constexpr abs() function

- meta/BrLToLGamma.m
- templates/l_to_lgamma.cpp.in
> remove hardcoded lepton name in l -> l gamma

- test/test_munuSSM.hpp
- test/test_munuSSM_gmm2.cpp
I've moved the changes to a new branch. The input is also defined now as a raw string.
> last changes to munuSSM g-2 test from Expander

- meta/CXXDiagrams.m
Hopefully the patch is self explainatory.
> fixed bug in splitting of cxxVertices list

- test/test_linalg2.cpp
> test/test_linalg2.cpp: avoid duplicate test function names

- meta/FlexibleSUSY.m
Ensure that the definition of unit_charge is always created, even when no code for calculation of observables (and therefore no code for vertices) is being written.
> fixed error with '--enable-shared-libs'

- test/test_MSSM_matching_selfenergy_Fd.meta
- test/test_MSSM_npointfunctions.meta
- test/test_SM_matching_selfenergy_Fd.meta
- test/test_SM_npointfunctions.meta
After testing of HiggsDecays some unhandled cases were reviled.
> Bugfix: code creation of vertices for npointfunction tests.

- src/numerics2.hpp
This is a variant of the code prepared by Dylan. It extends `is_zero` to work on complex numbers. I don't think it's currently used anywhere but since we have it and it doesn't cost anything, whould you be ok with including it into FS?
> is_zero version for complex numbers

- configure
- meta/FlexibleSUSY.m
Should solve #166.
Once this is accepted, I will merge it into #148 and then replace some bad things there.
Here, instead of just continuous appending of the new setups for variables the code looks, whether they exist in required files or not. If yes, it replaces settings, if not - appends.
> new metaflags added

- configure
- meta/FlexibleSUSY.m
> Bug in metaflag fixed

- configure
> Do not update `FlexibleSUSY.m` if there is no need

- src/module.mk
- src/slha_io.cpp
- src/slha_io.hpp
- src/string_conversion.cpp
- src/string_conversion.hpp
- test/module.mk
- test/test_slha_io.cpp
- test/test_string_conversion.cpp
This avoids large pieces of transitive dependencies on boost and STL headers
> break dependency on slhaea.h

- src/wrappers.hpp
- test/test_wrappers.cpp
* by ~50% for each beta function file
* by ~25% for all other files
> significantly reduce compile time for each file that includes wrappers.hpp

- meta/TerminalFormatting.m
It could look better, if we patch the `SARAH` code directly, but I think that it will be strongly version dependent.
> Fix for #234

- meta/NPointFunctions.m
- src/loop_libraries/libcollier_wrapper.cpp
- src/loop_libraries/library_collier.cpp
- src/loop_libraries/library_collier.hpp
- src/loop_libraries/library_fflite.cpp
- src/loop_libraries/library_fflite.hpp
- src/loop_libraries/library_looptools.cpp
- src/loop_libraries/library_looptools.hpp
- src/loop_libraries/library_softsusy.cpp
- src/loop_libraries/library_softsusy.hpp
- src/loop_libraries/loop_library_interface.hpp
- test/test_looplibrary.cpp.in
> Simpler realization of CD functions for LoopTools.

- test/test_CMSSM_librarylink_slha.sh
@Expander I think temporary files are not removed in this test.
> remove temporary files

- templates/decays.cpp.in
Now the function returns the correct value in the full range [0, infinity].
> Bugfix: correcting RT function Eq.(2.31) of hep-ph/0503172

- meta/Utils.m
- test/test_Utils.m
I've added to `Utils` function giving a sign of permutation. It's will become useful later.
> FSPermutationSign function

- model_files/cCMSSM/FlexibleSUSY.m.in
- test/test_cCMSSM.sh
The sign of a neutralino changes between the CMSSM and the cCMSSM
> fixing messy cCMSSM test

- .travis.yml
This fixes macOS test with gcc. How? No idea...
> fix travis macos gcc test

- meta/WriteOut.m
- templates/librarylink.cpp.in
- templates/run.cpp.in
- templates/run_cmd_line.cpp.in
- templates/slha_io.cpp.in
- templates/slha_io.hpp.in
This PR ensures that observables are not printed to SLHA output if they are not computed. Let me know what you think.
> Don't print empty observables

- meta/Vertices.m
- test/test_Vertices_SortCp.m
The `SortCp` doesn't handle `VVVV` vertices as produced by `CXXDiagrams`. This time it's not fault of `SortCp`. Jobst used different format for quartic gauge boson vertices
```mathematica
_QuadrupleVectorVertex,
{lIndex1, lIndex2, lIndex3, lIndex4} = LorentzIndexOfField /@
indexedFields;
vertexRules = {
(SARAH`Cp @@ sortedIndexedFields)[
SARAH`g[lIndex1, lIndex2] * SARAH`g[lIndex3, lIndex4]] ->
gaugeStructure[[1, QuadrupleVectorVertexPartForLorentzIndices[       
lIndex1, lIndex2, lIndex3, lIndex4]]],
(SARAH`Cp @@ sortedIndexedFields)[
SARAH`g[lIndex1, lIndex3] * SARAH`g[lIndex2, lIndex4]] ->
gaugeStructure[[1, QuadrupleVectorVertexPartForLorentzIndices[
lIndex1, lIndex3, lIndex2, lIndex4]]],
(SARAH`Cp @@ sortedIndexedFields)[
SARAH`g[lIndex1, lIndex4] * SARAH`g[lIndex2, lIndex3]] -> …
```
> SortCp for VVVV vertices comming from CXXDiagrams

- templates/mass_eigenstates.hpp.in
- templates/standard_model_matching.cpp.in
This bug fixes partially address [](https://github.com/FlexibleSUSY/FlexibleSUSY/issues/287)
A more complete fix still needs to be discussed there.
> FlexibleEFTHiggs ewsb bug fix

- meta/TreeMasses.m
Some helper functions that I'll need.
> added IsPhoton and IsZBoson functions

- src/lowe.cpp
- test/test_QedQcd.cpp
> fix running mt by pole Mt to avoid non-convergence

- model_files/munuSSM/LesHouches.in.munuSSM
New default munuSSM point with mAh(2) around 5.04 GeV.
> changed munuSSM default point

- templates/run.cpp.in
- templates/run_cmd_line.cpp.in
@pathron, please check if it does what you want.
> override flag 23 if we calculate observables

- model_specific/SM/weinberg_angle.cpp
- src/convergence_tester_drbar.hpp
- src/ew_input.hpp
- src/gm2calc_interface.cpp
- src/lowe.cpp
- src/mathdefs.hpp
- test/test_QedQcd.cpp
Please check this solution. You might object as you don't like including too many header files.
> removed M_PI

- createmodel
> Soft links for model_files can be used.

- configure
> Fix an unfortunate behavior of configure script

- configure
- meta/FlexibleSUSY.m
- meta/Utils.m
With `Mathematica 11` I can suggest to use this simple warning, so that PR #222 might be closed.
> Fancy warnings and errors.

- configure
> Check for an equality of timestamps.

- configure
- createmodel
Fixes the bug, introduced by me in #383.
Time is a complicated thing.
1) When creating a model, then we make sure, that time difference between `FlexibleSUSY.m` and `module.mk` is large (1 minute)
2) Now the `module.mk` is updated, if time difference from `FlexibleSUSY.m` is **larger** then `date_tolerance` variable.
> More specific definition for `newer`.

- meta/FlexibleSUSY.m
- meta/Utils.m
- meta/Wrappers.m
- meta/module.mk
- test/module.mk
- test/test_SM_vvvv.m
> Warning for a weird Lorentz index combination.

- meta/Constraint.m
- src/problems.cpp
- src/problems.hpp
> use the user-provided precision in the root finder and minimizer

- meta/CXXDiagrams.m
We had a check
```mathematica
Utils`AssertWithMessage[colourRep1 == colourRep2,
"CXXDiagrams`ConvertColourStructureToColorMathConvention[]: " <>
"Two colour indices in Kronecker delta that come from fields " <>
"of incompatible representations: Field1 = " <>
ToString[{colouredField1, colourRep1}] <> ", Field2 = " <>
ToString[{colouredField2, colourRep2}]];
```
to make sure that colour deltas have proper indices (so for example not triplet and octet indices together). `colourRep`\`s were obtained as
```mathematica
colourRep1 = SARAH`getColorRep[colouredField1];
colourRep2 = SARAH`getColorRep[colouredField2];
```
```SARAH`getColorRep``` returns a representation of a fundamental field (unbared/unconjugated) so, for example
```mathematica
SARAH`getColorRep[Fd] === SARAH`getColorRep[bar[Fd]] …
```
> identify colour deltas in models with 3 and -3 fields

- test/test_depgen.sh
> reduce number of newlines to exactly 1

- test/test_MSSM_2L_analytic.m
- test/test_SM_npointfunctions.cpp.in
- test/test_SM_tree_level_spectrum.cpp
- test/test_pv.cpp
- test/test_pv_crosschecks.cpp
These are various tweaks that got stuck on the #345. I think there is nothing too controversial here and they could me merged in.
> various unrelated changes from an unmerged PR

- .github/workflows/tests.yml
updating a base image to openSUSE 15.4
> CI tests with new base image

- src/slha_io.cpp
Hi @Expander. I'm not an expert on this so maybe you know. Isn't this the candidate to use `std::move`?
> move lvalue objects

- test/test_NUHMSSMNoFVHimalaya.cpp
using test points from arxiv:1708.05720
> Adding test for 3-loop fixed-order calculation in the MSSMNoFV with Himalaya

- templates/amm.cpp.in
> replace generate_scales by subdivide_log

- src/amm_loop_functions.cpp
- src/amm_loop_functions.hpp
- src/module.mk
- templates/amm.cpp.in
in order to allow for separate testing (against GM2Calc)
> Move Barr-Zee diagrams to separate module

- src/amm_loop_functions.cpp
with a factor 2 difference.
Note: The function `BarrZeeLoopV` is not implemented in GM2Calc and will be refined later.
> Feature: replace implementation BarrZeeLoopFPS by the one from GM2Calc

- meta/BrLToLGamma.m
- meta/FlexibleSUSY.m
- src/lowe.cpp
- src/lowe.h
to make the generated code more compact
> Feature: add getters for lepton pole/running masses

- src/ffv_loop_functions.cpp
- src/ffv_loop_functions.hpp
- src/module.mk
- templates/FFV_form_factors.cpp.in
to avoid code duplication and allow for systematic testing
> Move 1-loop functions for FFV to separate module

- src/decays/decay_functions.cpp
- src/lowe.cpp
- src/lowe.h
> Feature: adding index-based getters for up and down quark running masses

- templates/FFV_form_factors.cpp.in
Hi @dhjjacob,
I think this is a simple typo. We were returning $A_2^R$ instead of $A_1^R$. This doesn't solve the problem we've discussed by email though.
> fixed returned A2R instead of A1R form factor

- test/test_THDMII_GM2Calc.sh
now considering the Barr-Zee diagrams
> Adapt test for amu in the THDM-II

- src/amm_loop_functions.cpp
- src/amm_loop_functions.hpp
- templates/amm.cpp.in
- test/test_amm_loop_functions.cpp
and move them to a sub-namespace, similar to the FFV loop functions
> Simplification of BarrZeeLoopV

- meta/WeinbergAngle.m
- templates/weinberg_angle.cpp.in
- test/test_SM_mw_calculation.cpp
> correctly subtract SM contribution to mW

- model_specific/SM/standard_model.cpp
- model_specific/SM/standard_model.hpp
- model_specific/SM/weinberg_angle.cpp
- model_specific/SM/weinberg_angle.hpp
- src/error.hpp
- src/problems.cpp
- src/problems.hpp
- test/module.mk
- test/test_SM_weinberg_angle_meta.cpp
- test/test_standard_model_G_fermi.cpp
This PR re-introduces the prediction of the Fermi constant $G_F$ from known values of $M_W$, $M_Z$, $\alpha_{em}$ etc. It is needed for FlexibleEFTHiggs-3L.
> Feature: Predict G_F

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature-proposal.md
(currently there is only one for NPointFunctions)
> Feature: Adding two new github issue templates

- model_specific/SM/standard_model.cpp
The W boson pole mass calculation may depend on the predicted Higgs pole mass. Thus, both the W and the Higgs pole masses cannot be calculated in parallel but must be calculated in order.
fixes #603
> Fix race-condition in mw_pole calculation in the pre-generated SM

- meta/FlexibleSUSY.m
Fixes #609 by loading `NPointFunctions`.
> Fix to #609

- AUTHORS
- examples/new-observable/btosmumu/BrDLToDL/FlexibleSUSY.m
- examples/new-observable/btosmumu/br_d_l_to_d_l.cpp.in
- examples/new-observable/make-observable
- meta/NPointFunctions.m
I have added a few last important things that might be useful for current phenomenology projects with NPF.
> Ignore SM contributions for NPointFunctions. Some improvements in make-observable script.

- meta/FlexibleSUSY.m
- model_files/NMSSMEFTHiggs/FlexibleSUSY.m.in
- test/test_NMSSMEFTHiggs.cpp
when 3-loop corrections to Mh enabled.
> Activate 3-loop RGEs in the NMSSM
