FlexibleSUSY/FlexibleSUSY

src/wrappers.hpp
Also sort alphabetically std headers.
This header is required to std::accumulate.
=> Add missing numeric header.

configure
The `$CPATH` and `$CPLUS_INCLUDE_PATH` are environment variables which can be used to indicate additional locations for headers (for example, if they are installed in `~/.local/include`).
The commit also changes `default_lib_paths` and `default_inc_paths` to be Bash arrays so that they may be iterated over.  This is used in the case of `eigen3` to search the `eigen3` subdirectory of all default include paths (so for example, it will search in `~/.local/include/eigen3`), instead of just the usual system paths.  If you need to keep strict POSIX shell compliance, I can always amend the pull request to remove the use of arrays.
As part of the change to arrays, I had to change the array is passed `check_header` and `check_library`.  Alternatively, I could change the functions themselves to …
=> Use the CPATH environment variable to search for headers

meta/GMuonMinus2.m
Fixed an issue converting a SARAH index range (starting at 1) to a c++ index range (starting at 0).
=> Fixed off-by-one index issue

meta/FlexibleSUSY.m
M. Bach is already mentioned as an author in the documentation but was not shown as such when loading FlexibleSUSY yet.
=> Add M. Bach as an author, sort alphabetically

meta/CXXDiagrams.m, meta/EDM.m, meta/FlexibleSUSY.m, meta/SelfEnergies.m, meta/Vertices.m, src/concatenate.hpp, src/find_if.hpp, src/multiindex.hpp, templates/a_muon.cpp.in, templates/cxx_diagrams.hpp.in, templates/cxx_qft/context_base.hpp.in, templates/cxx_qft/fields.hpp.in, templates/cxx_qft/qft.hpp.in, templates/cxx_qft/vertices.hpp.in, templates/edm.cpp.in, templates/module.mk, templates/module.mk.in
- Make CXXDiagrams stateless
- Do not rely on SARAH`Vertex[]. Instead read the vertices directly from SARAH`VertexList* (dramatic speed increase)
- Give the c++ code a nicer structure
- Adapt the existing code to the new interfaces (still almost the same)
The changes should not affect any results. Could you please do the unit testing (I am unfamiliar with the framework - and doing this on the local cluster would be difficult...)?
=> Fix some outstanding issues with CXXDiagrams.

configure
Linking against `LoopTools` compiled with `ifort` yields (among others) the following error
```
undefined reference to 'getenv_'
```
As far as I understand, the problem is that contrary to `gfortran` where everything is in `libgfortran` library intel splits it into multiple ones: `libifort`, `libifport` and others. According to [this](http://ladon.iqfr.csic.es/intel/doc/main_for/mergedProjects/bldaps_for/files_32.htm) `ifport` provides "portability and POSIX support" so it kind of makes sense that adding it  solves the problem with `getenv`.
=> fixed linking with ifort compiled LoopTools

meta/CXXDiagrams.m
This function is needed for the work towards calculating colour factors as it can be used to reveal which colour (or arbitrary gauge group) indices from fields "at a given vertex" are contracted with corresponding indices at another (or the same) vertex. 
More generally, having access to the contractions is in some cases necessary to unambiguously identify the diagram in question -- Note that this information has always been available, but not in an obvious way.
The name of the function is terribly long, but every function argument is necessary...
=> Add function to access specific contractions of a diagram.

meta/CXXDiagrams.m, meta/FlexibleSUSY.m, meta/Vertices.m
Title says it all. This does not break g-2 or edm any more than it already was in the presence of non-trivial colour structures in the corresponding calculations. Such structures would have led to non-compiling code before this commit and now it is (again) correctly tracked in issue https://github.com/FlexibleSUSY/FlexibleSUSY/issues/24.
=> Add a flag to re-enable stripping of colour structures from vertices and use it.

configure
This avoids a failure of `./configure --disable-meta` if Mathematica is not available.
=> checking for FeynArts/FormCalc only if meta code generation is enabled

configure
This should work now with the new and the old FeynArts/FormCalc versions by checking first whether the symbol is a list or not.
=> Fix version check of FeynArts/FormCalc

meta/NPointFunctions/internal.m
Starting with FormCalc-9.6, the FeynArts`Mass convention has changed. This should fix the FormCalc to FS replacement rule. @iolojz could you have a look at this?
=> NPointFunctions: Adapt mass rule to FormCalc-9.6 and newer

templates/a_muon.cpp.in, templates/cxx_qft/vertices.hpp.in, templates/edm.cpp.in
Rename `Vertex<...>::field_indices()` to `Vertex<...>::indices_of_field()`. This is less ambiguous, because there also is a type called `field_indices`. It also makes the intel compiler happy.
=> Fix the intel compiler issues with CXXDiagrams

meta/CXXDiagrams.m
There was a bug causing the function to crash, if the given topology contained a loop with only one vertex. It also used to crash whenever no diagrams could be found as well as when there were no open fields to determine.
Also avoid using `AllTrue[]`
=> Some fixes to FeynmanDiagramsOfType[]

meta/NPointFunctions/internal.m
First of all, the FFV couplings from FormCalc are not translated into SARAH/FS couplings. My proposal is to remove the Lorentz structure and keep the information about left and right projection as usual.
Secondly with FormCalc-9.7, the internal convention for generic SSV couplings has changed. Commit 1701bd8 should add the missing rule.
=> NPointFunctions: Add rule for FFV couplings and additional rule for SSV couplings (FormCalc 9.7)

meta/EDM.m, meta/NPointFunctions.m, templates/a_muon.cpp.in, templates/cxx_qft/context_base.hpp.in, templates/cxx_qft/npointfunctions.hpp.in, templates/edm.cpp.in
Until now `context_base` only stored a reference to a `mass_eigenstates` object due to "performance" reasons. This is a really bad idea as I managed to produce undefined behaviour in my code and it took myself two hours to find out what the issue was... Therefore, we now simply store the whole `mass_eigenstates` object inside `context_base`. This does not affect performance at all because copies are cheap.
Also add a missing header to `templates/edm.cpp.in`
=> Two cxxdiagrams fixes

meta/Vertices.m, test/module.mk, test/test_Vertices.m, test/test_Vertices_SortCp.m
@Expander, @iolojz and me need a function that checks if a field index is a color index. We wrote our own versions but turns out that @jhyeon already had a much better one. We only need to expose it. I also added some unit tests. I wasn't sure where to put them, though. For now they are in the  `test/test_Vertices_SortCp.m` but this doesn't make sense.
=> exposed SarahColorIndexQ function

meta/CXXDiagrams.m, templates/a_muon.cpp.in, templates/edm.cpp.in
This should fix bug https://github.com/FlexibleSUSY/FlexibleSUSY/issues/69.
@wkotlarski Can you confirm this?
@Expander I have tested that amuon returns the same values as before in the SM and MSSM. I could do the same for edm in MSSMCPV next week. @wkotlarski If you need this fix earlier, you need to check it yourself.
=> Fix CXXDiagrams`FeynmanDiagramsOfType[] complex-conjugation issue

meta/NPointFunctions.m, templates/cxx_qft/npointfunctions.hpp.in
At the moment, the NPointFunctions module only supports integers for colour factors. This commit should extend it to complex fractional numbers.
@iolojz can you have a look at this?
=> NPointFunctions: support complex colour factors

test/test_MSSM_npointfunctions.meta, test/test_SM_cxxdiagrams.meta, test/test_SM_npointfunctions.meta
Currently, the path for `createdVertices` is wrong. This can cause duplicate definitions of vertices.
@iolojz can you have a look at this?
=> test: npointfunctions: fix path for createdVertices

.gitattributes
The `ScalarLeptoquarks` model, which is now part of the `development` branch, has not yet been thoroughly tested. It is still useful for testing though, since it produces non-trivial color factors for observables. We might therefore want to exclude it from releases for now.
=> excluding ScalarLeptoquark model from release

src/ew_input.hpp
This declares most of the numerical constants in the `ew_input.hpp` file as `constexpr` as discussed in issue #86.
=> ew_input: use constexpr for various constants

meta/AMuon.m, meta/FlexibleSUSY.m, meta/Observables.m, templates/a_muon.cpp.in, templates/a_muon.hpp.in, templates/l_to_lgamma.cpp.in, test/module.mk, test/test_munuSSM.hpp, test/test_munuSSM_gmm2.cpp
This addresses problem discussed in #82. Since we need an access to muon mass from the input file an `softsusy::QedQcd` needs to be passed around.
=> replace muon pole mass in a_mu

test/test_munuSSM_gmm2.cpp
There is a problem with a stability of the result while changing systems/compilers. I find that the relative differences are of the order of 10<sup>-8</sup>. This is something I actually wanted to talk to you about. `FlexibleSUSY` loses half of digits of precision before we get a final result. That is weird.
=> Fix reduce precision of amu test

templates/l_to_lgamma.hpp.in, test/test_MRSSM2.hpp, test/test_MRSSM2_gmm2.cpp, test/test_MRSSM2_l_to_lgamma.cpp, test/test_SM_gmm2.cpp, test/test_munuSSM.hpp, test/test_munuSSM_gmm2.cpp
This pull request fixes `SM` and `MRSSM2` units for g-2. It also removes `lowe.h` from being included in the `test_munuSSM.hpp`.
=> fixing unit tests for amu with MRSSM and SM

meta/CXXDiagrams.m, meta/FlexibleSUSY.m, meta/TreeMasses.m, templates/FFV_form_factors.cpp.in
Currently, we have the `IsSMParticle` function which asks `SARAH` whether the field multiplet is a SM multiplet or not. For BSM models the Higgs multiplets are labeled as `False` by default. @wkotlarski and I think that it is reasonable to assume that the first field in the charged Higgs and pseudoscalar Higgs multiplet are SM Goldstone bosons. This is important to avoid overcounting in the `FFVFormFactor` module.
This is a temporary fix until we have a good `IsSMParticle` check at runtime.
=> TreeMasses: Add IsSMParticleWithGoldstone

addons/GM2Calc/module.mk, addons/test_call_tsil/module.mk, config/Makefile.in, config/module.mk, doc/manuals/module.mk, doc/models/module.mk, doc/module.mk, examples/module.mk, fflite/module.mk, model_specific/MSSM_higgs/module.mk, model_specific/MSSM_thresholds/module.mk, model_specific/NMSSM_higgs/module.mk, model_specific/SM/module.mk, model_specific/SM_thresholds/module.mk, model_specific/SplitMSSM/module.mk, slhaea/module.mk, src/module.mk, templates/module.mk.in, test/SOFTSUSY/module.mk, test/module.mk
I propose to make the output of `make` less verbose. With this pull request `make` lists the compiled file(s), but (by default) omits the longish build command. This change improves the readability of the output of make and makes it for example easier to spot errors.
The verbose output can be re-enabled as in CMake by running
make VERBOSE=1
=> Feature: less verbose make output

meta/LoopMasses.m, meta/ThresholdCorrections.m, model_specific/SM/standard_model.hpp, src/database.hpp, src/error.hpp, src/lattice_solver.hpp, src/rkf_integrator.hpp, templates/a_muon.cpp.in, templates/librarylink.cpp.in, templates/observables.cpp.in, templates/run.cpp.in, templates/semi_analytic_ewsb_solver.hpp.in, templates/spectrum_generator_interface.hpp.in, templates/standard_model_spectrum_generator_interface.hpp.in, templates/two_scale_ewsb_solver.hpp.in, templates/utilities.cpp.in, test/SOFTSUSY/diagonalization.hpp, test/SOFTSUSY/numerics_legacy.cpp, test/module.mk, test/test_CMSSMMassWInput_spectrum.cpp, test/test_CMSSM_spectrum.cpp, test/test_NMSSM_spectrum.cpp, test/test_NUTNMSSM_spectrum.cpp, test/test_error.cpp, test/test_two_scale_mssm_solver.cpp
and make the exception classes trivially (nothrow) constructible as strongly proposed by the STL and https://www.boost.org/community/error_handling.html .
=> make flexiblesusy::Error inherit from std::runtime_error

meta/EffectiveCouplings.m
Super simple thing. Unify a way how we check if an index is a color/lorentz index.
=> replaced explicit search for color and lorentz indices by calls to appropriate functions

test/module.mk, test/test_linalg2.cpp
This pull request addresses issue #110 by reducing the maximal amount of resources (i.e. memory) that `test/test_linalg2.cpp` takes to compile.  The source file is split into 8 parts which are compiled into separate object files.  In the development branch, g++-7.3.1 consumes about 7GB of vsize to compile `test/test_linalg2.cpp`.  In this branch, the compilation of each part takes about 3GB or less.
=> Cheaper test/test_linalg2.cpp

meta/CXXDiagrams.m
This solves the problem raised by @dhjjacob in #115. You might accept this pull request as is. Alternativelly, I also wrote a function called `MathIndexToCPP` that secures the conversion of array indices from `mathematica` convention to `c++`. Such conversion is done in few places in the code. I can also add it in this pull request as it goes well with this previous fix.
=> search for field in vertex only at level 1

meta/CXXDiagrams.m, meta/Utils.m
This pull request brings in a ``Utils`MathIndexToCPP`` function that should be used throughout the code to convert interer literal index from `mathematica` to `c++` convention. This improves the previous way of doing this where we explicitly subtracted 1. The problem with this approach is that in this context, if the index was not an integer, this was obviously an error. Yet it was never checked. `MathIndexToCPP` checks the type of supplied argument. Not only whether the index is an integer but also wheter it's bigger than 0. If not, we call fancy error printout functions from @uukhas. Because of that, this pull request brings in also some updates to those functions from @uukhas.
=> added function converting array index from mathematica to c++ convention

meta/FunctionModifiers.m, templates/mass_eigenstates_decoupling_scheme.hpp.in, test/module.mk, test/test_FunctionModifiers.m
@Expander This pull request fixes warnings about override keywoard generated by clang. I'm not 100% sure what was the logic behind the original  implementation of `MakeOverride` function so would you mind having a look at my changes?
=> fixed clang override warning

meta/TestSuite.m
@Expander I'm not sure if not quiting from `TestEquality` is conceptually justified. It's not a failing test. It's a wrongly formatted test. But If I understand correctly we need it because of the way how tests works. Ps. Do we test a test framework? :)
=> bulletprooferd TestEquality function

.gitattributes
github incorectly identified a lot of `.m` files as matlab
=> fix what programing languages are reported on github

meta/TreeMasses.m, test/module.mk, test/test_MRSSM_TreeMasses.m
There's also one change which might be of (minor) interest to some. The getters for certain particles (like `GetPseudoscalarHiggsBoson`) return `Null` if a given particle does not exist in a model. Not a new, undefined symbol like potentially ```SARAH`PseudoScalarBoson``` could be nor do they quit the kernel. It's up to the caller to decide how to handle it.
=> unit test for the TreeMassess module in the MRSSM

src/sum.hpp
=> fixing bug in SUM() macro for clang++ 7.0

meta/Utils.m, test/module.mk, test/test_Utils.m
It is possible using Mathematica to specify the input of functions in absolutely concrete way.
The bad side of this is that for all functions one has to write func[args___] case, which leads to
terminating of mathematica session (or some other behavior). Plus, one would like to get some relevant output before termination
telling about details of an error. It is possible to do this manually for all functions, but it requieres
a lot of time and slows down code implementation and leads to wish of writing a code in a "cowboy" style.
This is why I suggest to add and use MakeUnknownInputDefinition function (the current name is just a suggestion) to
speed this up and make Mathematica part of evaluation **safer**.
It should be used in the following way:
```
myFunc::usage = "text";
more messages …
```
=> New function for making definition for manually unhandled input.

test/module.mk
With `--disable-librarylink` `test_flexiblesusy-config.sh` fails with
```
test/SM/SM_librarylink.cpp:43:10: fatal error: mathlink.h: Nie ma takiego pliku ani katalogu    
43 | #include <mathlink.h>    
|          ^~~~~~~~~~~~    
```
I think it should be also secured by `ENABLE_LIBRARYLINK`
=> don't run flexiblesusy-config test if --disable-librarylink

meta/CXXDiagrams.m, meta/FlexibleSUSY.m, templates/cxx_qft/context_base.hpp.in, templates/mass_eigenstates_interface.hpp.in
This PR adds the function that gets physical mass of particle from `context`. It's an analogue of already existing function that gives a tree-level mass. The only tricky point is that `get_physical()` which is used in `context_base.hpp`  doesn't seem to work with a forward declaration of `@ModelName@_physical` so I had to include `@ModelName@_physical.hpp` in `@ModelName@_mass_eigenstates_interface.hpp`.
=> physical mass getter from context

meta/FlexibleSUSY.m, model_files/THDMII/FlexibleSUSY.m.in
@Expander, I noticed by accident that there is an error in setup of `THDMII` model. In `FlexibleSUSY.m.in` there's a line that says
```
HighPoleMassPrecision    = {hh, Ah, Hpm};
```
But there is no `Hpm` in this model. It should say `Hm`. This PR introduces a fix for this and a function that check `HighPoleMassPrecision` and similar variables. Are you ok with that and do you have a suggestion where such function should be used? Right now I'm checking
```
{HighPoleMassPrecision, MediumPoleMassPrecision, LowPoleMassPrecision}
```
=> validate content of PoleMassPrecision variables

sarah/SMSU3/SMSU3.m, sarah/SMSU3/particles.m
Dylan added a function that checks if PDG number list for particle agrees with the size of the multiplet. This uncovered what I believe is an error in `particle.m` for `SMSU3` model.
=> fixed error in SMSU3 particle file

meta/TreeMasses.m
Currently, in `MSSM` function `GetDimensionStartSkippingGoldstones` incorectly handles conjugations. Example
```mathematica
GetDimensionStartSkippingGoldstones[Hpm] = 2
GetDimensionStartSkippingGoldstones[conj[Hpm]] = 1
```
Similarly for `GetDimensionWithoutGoldstones` which gives
```mathematica
GetDimensionWithoutGoldstones[Hpm] = 1
GetDimensionWithoutGoldstones[conj[Hpm]] = 3
```
This fix makes those function give the same number with and without `conj`.
=> Fix multitple size getters without Goldstones

.travis.yml, configure
This branch aims to fix the `make install-src` command, see issue #171.
The following should work:
~~~
for i in 1 2 3
do
./configure --with-models=SM --with-install-dir=install
make
make install-src
cd install
done
~~~
=> Fix make install-src

templates/module.mk.in
At first meta phase file `vertices.mk` is not created, so it shouldn't be called.
=> Bug fix of #185 

templates/run.cpp.in
Now the observable block is not printed unless we calculate observables. This messes up with some tests.
=> compute observables only if spectrum was generated

meta/FlexibleSUSY.m, meta/TerminalFormatting.m, meta/module.mk
Allows to have cleaner terminal output of `SARAH`.
In this package some `Dynamic` were upvalued, so that inside terminal there is no "broken" output from `SARAH`.
=> less messy sarah output to terminal

meta/NPointFunctions.m, test/module.mk
I noticed, that 
```
NPointFunctions`internal`GenerateFAModelFileOnKernel: errUnknownInput:
Usage:
@brief Generate the FeynArts model file on a given subkernel.
The behavior for case
1) GenerateFAModelFileOnKernel[kernel_Parallel`Kernels`kernel]
is defined only.
Call
GenerateFAModelFileOnKernel[KernelObject[1, local]]
is not supported.
Wolfram Language kernel session terminated.
```
is generated by tests. This is weird, because `KernelObject[1, local]` _has_ the head ``Parallel`Kernels`kernel`` in `FullForm`.
=> fix: error when KernelObject is not represented in FullForm.

test/test_MSSM_matching_selfenergy_Fd.cpp.in, test/test_MSSM_npointfunctions.cpp.in, test/test_SM_cxxdiagrams.cpp.in, test/test_SM_matching_selfenergy_Fd.cpp.in, test/test_SM_npointfunctions.cpp.in, test/test_looplibrary.cpp.in
This fixes issues similar to #204
=> Ensure a main() is generated for all tests that use Boost.Test

meta/Parameters.m
This PR makes `GetPDGCodesForParticle` from `Parameters.m` correctly handle `conj` and `bar` heads. Anyone knows why it was never a problem? What is now seems wrong yet somehow no one has ever stumbled upon it?
=> handle conj/bar in GetPDGCodesForParticle

meta/FlexibleSUSY.m, templates/info.hpp.in, test/module.mk, test/test_MSSMCPV_SARAH.m
This PR adds info whether a model has a CP violating Higgs sector. This information is needed for decays. I called the variable `CPViolationInHiggsSector`. Let me know if you're ok with this.
=> flag models with CP violating Higgs sector

meta/Utils.m, meta/Vertices.m, test/test_SM_cxxdiagrams.meta
I think there might be a sign error in `VVV` vertices.
`Vertex[{conj[VWp], VWp, VZ}]` gives
```mathematica
{
{conj[VWp[{lt1}]], VWp[{lt2}], VZ[{lt3}]}, 
{I g2 Cos[ThetaW], 
g[lt1, lt2] (-Mom[conj[VWp[{lt1}]], lt3] + Mom[VWp[{lt2}], lt3]) + 
g[lt2, lt3] (-Mom[VWp[{lt2}], lt1] + Mom[VZ[{lt3}], lt1]) + 
g[lt1, lt3] (Mom[conj[VWp[{lt1}]], lt2] - Mom[VZ[{lt3}], lt2])
}
}
```
while `Vertex[{VWp, conj[VWp], VZ}]` gives
```mathematica
{
{VWp[{lt1}], conj[VWp[{lt2}]], VZ[{lt3}]}, 
{-I g2 Cos[ThetaW], 
-g[lt1, lt2] (-Mom[conj[VWp[{lt2}]], lt3] + Mom[VWp[{lt1}], lt3]) - 
g[lt2, lt3] (Mom[conj[VWp[{lt2}]], lt1] - Mom[VZ[{lt3}], lt1]) - 
g[lt1, lt3] (-Mom[VWp[{lt1}], lt2] + Mom[VZ[{lt3}], lt2])
}
}
```
If you look only a the value of the coupling, not the lorentz structure, then they differ by sign. …
=> fixed permutation of VVV vertices

config/module.mk, configure
to fix a compilation error with boost 1.74
fixes #267
=> rename config/version to config/flexiblesusy-version

model_files/SSMMhInput/FlexibleSUSY.m.in
In the `SSMMhInput` lambda is set at the low scale by solving for the Higgs pole mass input using
```mathematica
FSFindRoot[{\[Lambda]}, {MhInput - Pole[M[hh[1]]]}]
```
The problem is that before you get to the SUSY scale, you collect enough logs that the pole mass is no longer `MhInput`. In the default input, this gives 0.5 GeV shift for `MhInput` = 125 GeV. Maybe the procedure in this PR would be better? I had to also give a starting value for `lambda` at the low scale, otherwise it doesn't work.
=> tweak SSMMhInput to give correct Higgs mass at the SUSY scale

src/eigen_utils.hpp, test/test_eigen_utils.cpp
diagonalization.  The function `reorder_vector` now uses the component-wise magnitude for the ordering.
Note: This changes the behavior of low-precision pole mass calculation in case of running tachyons.
fixes #281
=> fix compilation error in CPV models with LowPrecision scalar mass

configure
This aims to fix the problem here https://github.com/FlexibleSUSY/FlexibleSUSY/issues/292 .
@azedarach helped find the right use of sed etc on the macOS, but I will need to get a BigSur user to test it before we can merge it in (i will see if my GAMBIT collaborator Jonathan Cornell can after he has tested a similar fix in GAMBIT).  In the meantime Alex will probably want to look at the very ugly way I do this, though and may have comments.
Finally it only fixes the issue of not finding the library.  For the FS - 2.0.1 in gambit I have also made a change so that if the pthread libs are not found it simply disables multi-threading (as long as it was not explicitly enabled) instead of always giving a configure error.  I think we should do something similar in FS but the configure script has …
=> Fix macOS BigSur configure problem finding pthreads

configure
to not require the user to set `LD_LIBRARY_PATH` every time
=> link COLLIER, LoopTools and TSIL with rpath

doc/librarylink.rst
Please not that before we used the `::` to define a code block. `::` prints a single `:` at the end of line. The `.. code-block` syntax does not. If we want to retain those `:` we need to add the explicitly.
=> mathematica syntax highlighting in librarylink.rst

README.rst, configure
because the symbol `StringPadRight` seems to be defined only from version 10 onward.
=> update required Mathematica version to 10

templates/FFV_form_factors.cpp.in, templates/l_to_lgamma.cpp.in
Small optimization in a_mu calculation:
* replace `pow` function calls by faster `Power*` functions
* avoid re-evaluation of 1-loop functions
=> Optimization of FFV calculation

doc/references.bib, meta/FlexibleSUSY.m
Since we use a modified version of ColorMath in FlexibleDecay I think it's fair we add it to the auto-generated reference list if we compute decays.
=> added ColorMath reference to the list of references

meta/CXXDiagrams.m, meta/ColorMath.m, meta/Decays.m, model_files/MRSSM2/FlexibleSUSY.m.in, templates/decays/decays.hpp.in, test/test_MRSSM2_FlexibleDecay.cpp
This PR partially solves the issue #260. For decays to a symmetric final state we can predict that the amplitude is only proportional to d. In the MRSSM this allows to generate sgluon -> gg decays.
=> working decays of octet to gg

meta/FlexibleSUSY.m, templates/run_cmd_line.cpp.in
`run_cmd_line_*` was never actually computing decays because it never called `calculate_decays()`. Since there is no switch in `run_cmd_line_*`  that controls whether we do or don't want decays calculated, I also had to add
```
settings.set(Spectrum_generator_settings::calculate_sm_masses, 1.0);
```
in all cases as decays need those masses.
=> fix decay calculation via run_cmd

model_files/lowNMSSM/FlexibleSUSY.m.in, model_files/lowNMSSMTanBetaAtMZ/FlexibleSUSY.m.in
Some lines where duplicated in low scale NMSSM model files
```mathematica
SUSYScaleInput = {    
.....  
{me2[1,1], me1Input^2},    
{me2[2,2], me2Input^2},    
{me2[3,3], me3Input^2},    
...
{me2[1,1], me1Input^2},    
{me2[2,2], me2Input^2},    
...
};    
```
=> removed duplicate lines in lowNMSSM model files

configure
`NPointFunctions` relies of `FeynArts` and `FormCalc`.
Some output is cached.
If the version of `FeynArts` and `FormCalc` changes, then this cache should be removed for **all** models.
Connected to #369.
=> Clearing cache for FeynArts and FormCalc for different version.

.clang-tidy, .github/workflows/tests.yml
As I remember someone once tried to sort header includes and people didn't like it so we might suppress this warning.
=> supress clang-tidy warning about unsorted header includes

configure
Do not run Mathematica if there is no need. 
The only type of the input, when this approach fails, happens if user splits the flags.
For example, for `UseHiggs2LoopNMSSM` it might be like this:
```mathematica
With[{lhs=ToExpression["Use"<>"Higgs2LoopNMSSM"]},
lhs = True;
];
```
But I assume, that this happens almost never.
=> Speed up `get_model_specific_corrections`.

meta/NPointFunctions.m, meta/Utils.m, test/test_Utils.m
I wanted to extend a bit some functions, which I wrote long ago: `AssertOrQuit`, `MakeUnknownInputDefinitions`, `EvaluateOrQuit` (maybe it was even my first PR).
The `::usage` was unreadable, the code was a nightmare. One function even seems to be non-working now. 
This PR fixes it and make it user and developer friendly.
=> Simplify error functions

meta/FlexibleSUSY.m, src/decays/H_SM_decays/decay_AH_to_AA.inc, src/decays/H_SM_decays/decay_AH_to_AZ.inc, src/decays/H_SM_decays/decay_AH_to_GG.inc, src/decays/H_SM_decays/decay_AH_to_dqdq.inc, src/decays/H_SM_decays/decay_AH_to_leplep.inc, src/decays/H_SM_decays/decay_AH_to_uquq.inc, templates/info.hpp.in, test/test_MRSSM2_FlexibleDecay.cpp, test/test_MSSMCPV_FlexibleDecay.cpp, test/test_MSSM_FlexibleDecay.cpp, test/test_THDMII_FlexibleDecay.cpp
Hi @Expander 
IMO this PR should go before others we are now discussing (#409, #410). Here's what was fishy. In an autogenerated code we made sure that we do not generate decays of Goldstone bosons. But you can still call them by hand, as was done in some test. This PR makes sure it cannot happen. If you try this, you'll get something like
```
unknown location(0): fatal error: in "test_MRSSM2_FlexibleDecay": flexiblesusy::OutOfBoundsError: Error in Ah(0)->{barFd(2),Fd(2)} decay. Decaying particle is a Goldstone.
```
I have implemented a simplest way to get the number of Goldstones in a multiplet but I'm happy to change it if you want it.
PS. I'm not 100% sure how it was related to the fact that after change of SM mW some Ah decays became 0. Only charged Goldstone should be controlled …
=> make sure that no one calls decay for a goldstone

model_files/MSSMMuBMu/FlexibleSUSY.m.in, model_files/MSSMMuBMu/LesHouches.in.MSSMMuBMu
Since in this model `\mu` is an input, I don't think we also need to input a sign of `\mu`.
=> removed unused input in MSSMMuBMu

test/test_scan.cpp
This fixes the following error
```
Building test/test_scan.o
test/test_scan.cpp: In member function ‘void uniform_distribution_0_1::test_method()’:
test/test_scan.cpp:48:26: error: variable ‘std::array<double, 1000> a’ has initializer but incomplete type
48 |    std::array<double, N> a{};
|                          ^
test/test_scan.cpp: In member function ‘void uniform_distribution_start_stop::test_method()’:
test/test_scan.cpp:62:26: error: variable ‘std::array<double, 1000> a’ has initializer but incomplete type
62 |    std::array<double, N> a{};
|                          ^
make: *** [Makefile:252: test/test_scan.o] Błąd 1
```
No idea why it appeared just now but it seems reasonable that this include should be there.
=> fixed missing include

.github/workflows/static-analysis.yml
```
SC3037 (warning): In POSIX sh, echo flags are undefined
SC3043 (warning): In POSIX sh, 'local' is undefined
```
=> disable shellcheck warnings SC3037 and SC3043

test/test_CMSSMSemiAnalytic_spectrum.sh
This test passes if we don't compute decays as they deviate quite strongly between `CMSSM` and `CMSSMSemiAnalytic`
[test_CMSSMSemiAnalytic_spectrum_CMSSM.out.spc.txt](https://github.com/FlexibleSUSY/FlexibleSUSY/files/8907115/test_CMSSMSemiAnalytic_spectrum_CMSSM.out.spc.txt)
[test_CMSSMSemiAnalytic_spectrum.out.spc.txt](https://github.com/FlexibleSUSY/FlexibleSUSY/files/8907116/test_CMSSMSemiAnalytic_spectrum.out.spc.txt)
@Expander, I propose to disable comparison of decays unless you want to track the source of difference.
=> remove comparison of decays from test_CMSSMSemiAnalytic_spectrum

CHANGES.rst, src/decays/H_SM_decays/decay_AH_to_uquq.inc, src/decays/H_SM_decays/decay_H_to_uquq.inc, test/test_MRSSM2_FlexibleDecay.cpp, test/test_MSSMCPV_FlexibleDecay.cpp, test/test_MSSM_FlexibleDecay.cpp, test/test_SM_FlexibleDecay.cpp, test/test_THDMII_FlexibleDecay.cpp
Wrong QED quark charge was used in higher order corrections. The difference is at a level of 0.03%.
=> error in H and A to uubar higher order corrections

src/decays/decay.cpp, src/decays/decay.hpp, templates/slha_io.cpp.in
to prevent a linker error when two model libraries are linked to one executable.
fixes #464
=> Move sort_decays_list

test/test_CMSSMNoFV_GM2Calc.sh
This clean-up should be merged into `development` and `enable-BarrZee-diagrams` for better comparison of amu when the 2-loop Barr-Zee diagrams are enabled.
=> Clean-up test of amu in CMSSMNoFV vs GM2Calc

templates/info.cpp.in
This fixed the
```
warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<int>::size_type' {aka 'long unsigned int'} [-Wsign-compare]
```
warning.
=> fixed compiler warning

templates/amm.cpp.in, test/test_CE6SSM_amm.cpp, test/test_MRSSM2_amm.cpp, test/test_munuSSM_amm.cpp
This change reproduces exactly the vertex originally written by Felix
```cpp
const double gvf = (0.5) * (zfzr.real()/unit_charge(context) - fermionChargeCount*sw/cw);
```
for leptons and quarks. It does give a different number for charginos though. And I think this might be ok. The original vertex looks like it always assumes that Z-couples to fermion via the covariant derivative (it always looks like a coupling of Z to SM-fermions). But this would not be ok for fermions like charginos.
=> replace hard coded Z-fermion vertex

meta/BrLToLGamma.m
Hi @uukhas
I think I've messed up and used a wrong mass as a prefactor. #479 changed the syntax for getting SM lepton masses and before it was easy to make a mistake (it was not super clear which mass is pole and which is not). So I think it was just a typo. Are you ok with this change?
=> use pole mass as prefactor in BrLToLGamma

meta/FlexibleSUSY.m, templates/lepton_amm_wrapper.cpp.in, templates/lepton_amm_wrapper.hpp.in, templates/module.mk, templates/module.mk.in, test/test_MRSSM2_gmm2.cpp
Since we now call `FlexibleSUSY` calculation of g-2 `AMM` maybe it makes sense to rename remaining occurrences of `gm2` to `amm`. We only leave untouched `gm2` in names related to `GM2Calc`
=> rename gm2 to amm

src/decays/decay.cpp, src/decays/decay.hpp
One thing that I'm still trying to figure out is whether
```cpp
A::A(T&& x) : x_{x} {}
```
is enough or does one have to explicitly call `std::move`
```cpp
A::A(T&& x) : x_{std::move(x)} {}
```
=> optimize creation of decay process name

configure
I'll ask Henning to be sure but I think that HiggsTools only builds shared library. This PR fixes the problem even if we compile FS into static library. Ideally, I would like to switch back to static
```
-Wl,-Bdynamic -lHiggsTools -Wl,Bstatic"
```
if we are building static library but I cannot. After this library there are others which have to be linked dynamically
```
clang++ -static -o models/SM/run_SM.x  /tmp/FS/models/SM/run_SM.o  /tmp/FS/models/SM/libSM.a  /tmp/FS/model_specific/SM/libmodel_specific_SM.a  /tmp/FS/src/libflexisusy.a  /tmp/FS/src/loop_libraries/libcollier_wrapper.a  /tmp/FS/src/libfortran_utils.a -L/home/kotlarskiw/HEP-software/COLLIER-1.2.7/lib -Wl,-rpath,/home/kotlarskiw/HEP-software/COLLIER-1.2.7/lib -lcollier  -L/home/kotlarskiw/HEP-software/HiggsTools-1.0/lib …
```
=> HiggsTools only builds a shared library

meta/Decays.m
I think there is a problem with the second branch of this `switch` statement
```cpp
if (run_to_decay_particle_scale) {
auto decay_mass = PHYSICAL(Mhh);
if (decay_mass > qedqcd.displayPoleMZ()) {
model.run_to(decay_mass);
model.solve_ewsb();
}
}
const int flag = 1;
auto dec_model = [&] () -> std::unique_ptr<SM_mass_eigenstates_interface> {
switch (flag) {
case 1: {
auto dm = std::make_unique<SM_mass_eigenstates_decoupling_scheme>(
model.get_input());
// fill_from BSM model has to be called before fill_from SM
// both calls are required
dm->fill_from(model);
standard_model::Standard_model sm{};
sm.initialise_from_input(qedqcd);
// set loop level for RGE running to match RGE setting
// of BSM model
sm.set_loops(model.get_loops());
if (run_to_decay_particle_scale) {
auto decay_mass = …
```
=> wrong masses in the non-decoupling scheme

model_files/MRSSM2/FlexibleSUSY.m.in
This PR adds an extra entry (number 10) to the `HMIX` block in the `MRSSM2`. Other entries will be identical to an autogenerated `HMIX` block. This entry is needed to pass spectrum file to CalcHEP.
=> missing entry 10 in HMIX block

CHANGES.rst, meta/FlexibleSUSY.m, src/always_false.hpp, src/decays/decay.hpp, src/decays/flexibledecay_settings.cpp, src/decays/flexibledecay_settings.hpp, src/decays/specializations/Ah/decay_Ah_to_AA.inc, src/decays/specializations/Ah/decay_Ah_to_AZ.inc, src/decays/specializations/Ah/decay_Ah_to_gg.inc, src/decays/specializations/H/decay_H_to_AA.inc, src/decays/specializations/H/decay_H_to_AZ.inc, src/decays/specializations/H/decay_H_to_gg.inc, src/module.mk, src/slha_format.cpp, src/slha_format.hpp, src/slha_io.cpp, src/slha_io.hpp, templates/decays/decays.hpp.in, templates/slha_io.cpp.in, templates/slha_io.hpp.in
This replaces PR  #404. It provides an `EFFHIGGSCOUPLINGS` that is read by SARAH generated UFO and CalcHEP (so also micrOMEGAs) models
```
Block EFFHIGGSCOUPLINGS
25          21          21     5.63154856E-05   # hh(1)-VG-VG
25          22          22     2.52221041E-05   # hh(1)-VP-VP
35          21          21     5.30370890E-05   # hh(2)-VG-VG
...
36          21          21     2.92231712E-05   # Ah(2)-VG-VG
36          22          22     1.01798470E-04   # Ah(2)-VP-VP
...
```
=> print EFFHIGGSCOUPLINGS block

model_specific/MSSM_higgs/mssm_twoloophiggs.cpp, test/test_MSSM_2L_limits.cpp
due to taking the sqrt of a negative number
=> Bugfix: Fix a numeric divergence in MSSM 2-loop contributions O(at*as)

configure, meta/FlexibleSUSY.m
We skip generation of decays if FlexibleSUSY was not configured with external loop library. But this check should be disabled if we disable compilation.
Closes #555.
=> decays should't check for loop libraries if disable compile

templates/two_scale_high_scale_spectrum_generator.cpp.in, templates/two_scale_low_scale_spectrum_generator.cpp.in
Hi @Expander. I think there are some redundant spaces here. Not sure why it even worked in the first place...
Sorry. My bad. Forget I've asked. It's a valid C++ code [see here](https://stackoverflow.com/questions/15410428/a-space-before-function-call-in-c) You learn something every day...
=> removed extra space in method call

configure
There is a built-in time delay of 5 seconds in `update_module_mk`, which causes problems: It may happen that the model-specific makefile module is not updated, which leads to a build error of the form:
~~~
Makefile:191: model_specific/@MODEL_SPECIFIC_MODULES@/module.mk: No such file or directory
make: *** No rule to make target 'model_specific/@MODEL_SPECIFIC_MODULES@/module.mk'.  Stop.
~~~
See for example #594 .
@uukhas You've created this time delay. What were the reasons for this?
This PR proposes to remove the time delay.
=> Bugfix: Time delay in update_module_mk

configure
This PR tries to make the discovery of `python3-config` more robust. On some systems there is no `python3-config` alias. Instead, only separate version for each python3 version exists, e.g. `python3.12-config`.
=> fix discovery of python3*-config

CHANGES.rst, model_files/MRSSM2/FlexibleSUSY.m.in, src/decays/decay.hpp, test/test_MRSSM2_FlexibleDecay.cpp
The color factor in decays where external states we a triple of octet-triplet-triplet was wrong. I've noticed it while comparing the output of FlexibleSUSY with the SModelS input created by micrOMEGAs. After the fix, we get:
**sgluon decay (to test 8->3 -3 decay)**
FlexibleSUSY
```
DECAY   3000021     1.08234431E+02   # phiO decays    
3.94954231E-01   2    -1000002   1000002  # BR(phiO -> conjSu(1) Su(1))    
3.94954128E-01   2    -1000004   1000004  # BR(phiO -> conjSu(2) Su(2))    
2.09746938E-01   2    -1000006   1000006  # BR(phiO -> conjSu(3) Su(3))    
1.47445791E-04   2          21        21  # BR(phiO -> VG VG)
```
micrOMEGAs
```
DECAY 3000021  1.218619E+02  # POc
3.950904E-01   2   1000002 -1000002  #  ~su1,~Su1 
3.950903E-01   2   1000004 -1000004  #  ~su2,~Su2 
2.098192E-01 …
```
=> fixed wrong color factor in TTO decays

CHANGES.rst, configure
Hey @Expander ,
This is just a guess but I think the problem that was reported in the last issue might be that `python3-config --libs --embed` doesn't return a lib directory, only libs themselves
```
-lpython3.10 -lcrypt -ldl  -lm -lm
```
in contrast to `python3-config --ldflags --embed` which gives
```
-L/usr/lib/python3.10/config-3.10-x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -lpython3.10 -lcrypt -ldl  -lm -lm
```
This PR might be a potential fix to the reported bug.
=> fix linking with libpython3

sarah/SM2/particles.m
SARAH is confussed about the charge of `Hp`
```
Vertex::ChargeViolating: 
Non-zero result for {Ah, Hp, conj[VWp]}
vertex which violates charge. (This might just be a problem with
simplifying the vertex, but could also point towards a mistake in the
implementation.)
Vertex::ChargeViolating: 
Non-zero result for {Ah, conj[Hp], VWp}
vertex which violates charge. (This might just be a problem with
simplifying the vertex, but could also point towards a mistake in the
implementation.)
Vertex::ChargeViolating: 
Non-zero result for {hh, Hp, conj[VWp]}
vertex which violates charge. (This might just be a problem with
simplifying the vertex, but could also point towards a mistake in the
implementation.)
General::stop: Further output of Vertex::ChargeViolating
```
=> fix SMHighScale model warning

.github/workflows/tests.yml, config/config.h.in, configure, test/test_SM_observable_problems.cpp
The signature of `calculate_observables` changes depending on whether FeynArts/FormCalc is enabled. There was a weird interplay between `--disable-meta` and FeynArts/FormCalc. I had to fix that too. I've also added tests with `--disable-feynars` and `--disable-formcalc`.
=> fix tests broken when FA/FC is disabled
